---
- name: Terminate Fortigate Instance
  amazon.aws.ec2_instance:
    state: absent
    filters:
      "tag:Name": "{{ fortigate_instance.name }}"

- name: Terminate FortiManager Instance
  amazon.aws.ec2_instance:
    state: absent
    filters:
      "tag:Name": "{{ fortimanager_instance.name }}"

- name: Gather VPC information
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ vpc.name }}"
  register: vpc_info

- name: Set VPC ID for deprovisioning
  ansible.builtin.set_fact:
    vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
  when:
    - vpc_info.vpcs is defined
    - vpc_info.vpcs | length > 0

- name: Gather Route Table information
  amazon.aws.ec2_vpc_route_table_info:
    filters:
      "vpc-id": "{{ vpc_id }}"
      "tag:Name": "{{ item.name }}"
  loop: "{{ route_tables }}"
  when: vpc_id is defined
  register: rt_info

- name: Delete Route Tables
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    route_table_id: "{{ item.route_tables[0].route_table_id }}"
    lookup: id
    state: absent
  loop: "{{ rt_info.results }}"
  when:
    - vpc_id is defined
    - item.route_tables is defined
    - item.route_tables | length > 0

- name: Gather Interface information
  amazon.aws.ec2_eni_info:
    filters:
      private-ip-address: "{{ item.ip_address }}"
  loop: "{{ interfaces }}"
  register: eni_info

- name: Delete Interfaces
  amazon.aws.ec2_eni:
    eni_id: "{{ item.network_interfaces[0].network_interface_id }}"
    state: absent
  loop: "{{ eni_info.results }}"
  when:
    - item.network_interfaces is defined
    - item.network_interfaces | length > 0

- name: Gather Security Group information
  amazon.aws.ec2_security_group_info:
    filters:
      "vpc-id": "{{ vpc_id }}"
      "group-name": "{{ item.name }}"
  loop: "{{ security_groups }}"
  when: vpc_id is defined
  register: sg_info

- name: Delete Security Groups
  amazon.aws.ec2_security_group:
    vpc_id: "{{ vpc_id }}"
    group_id: "{{ item.security_groups[0].group_id }}"
    state: absent
  loop: "{{ sg_info.results }}"
  when:
    - vpc_id is defined
    - item.security_groups is defined
    - item.security_groups | length > 0

- name: Gather Subnet information
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      "vpc-id": "{{ vpc_id }}"
      "tag:Name": "{{ item.name }}"
  loop: "{{ subnets }}"
  when: vpc_id is defined
  register: subnet_info

- name: Delete Subnets
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.subnets[0].cidr_block }}"
    state: absent
  loop: "{{ subnet_info.results }}"
  when:
    - vpc_id is defined
    - item.subnets is defined
    - item.subnets | length > 0

- name: Delete Internet Gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    state: absent
  when: vpc_id is defined

- name: Delete VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc.name }}"
    cidr_block: "{{ vpc.cidr_block }}"
    state: absent
  when: vpc_id is defined

# - name: Gather Fortigate public interface information
#   amazon.aws.ec2_eni_info:
#     filters:
#       "tag:Name": fntlab-eni-public-mgmt-1
#   register: public_eni_info

- name: Gather Fortigate EIP information
  amazon.aws.ec2_eip_info:
    filters:
      "tag:Name": "{{ fortigate_instance.eip }}"
  register: eip_info_fgt

- name: Diassociate Elastic IP from Fortigate instance
  amazon.aws.ec2_eip:
    # device_id: "{{ public_eni_info.network_interfaces[0].id }}"
    # in_vpc: true
    # release_on_disassociation: true
    ip: "{{ eip_info_fgt.addresses[0].public_ip }}"
    tag_name: Name
    tag_value: "{{ fortigate_instance.eip }}"
    state: absent
  when:
    - eip_info_fgt.addresses is defined
    - eip_info_fgt.addresses | length > 0


- name: Gather Fortigate EIP information
  amazon.aws.ec2_eip_info:
    filters:
      "tag:Name": "{{ fortimnager_instance.eip }}"
  register: eip_info_fmgr

- name: Diassociate Elastic IP from Fortigate instance
  amazon.aws.ec2_eip:
    ip: "{{ eip_info_fmgr.addresses[0].public_ip }}"
    tag_name: Name
    tag_value: "{{ fortigate_instance.eip }}"
    state: absent
  when:
    - eip_info_fmgr.addresses is defined
    - eip_info_fmgr.addresses | length > 0
